### ISSUE TITLE
Not able to locate install.sh file (as given for the installation step)

### ISSUE THREAD

**Issue by thesukantadey** [The-OpenROAD-Project/OpeNPDN#1]
`cd OpeNPDN`
`mkdir build`
`cd build` 
`cmake ..`
`cd ..`
`make clean`
`source install.sh`
`make test`

See the `source install.sh` command. No such file `install.sh` generated or located in the project directory. So how do we install the `OpenNPDN` package?

**Comment by VidyaChhabria** [comment]
This has now been added https://github.com/The-OpenROAD-Project/OpeNPDN/blob/standalone/install.sh

**Comment by thesukantadey** [comment]
Thanks, Vidya. It worked. Hoping to use it and develop further.
